name: Scala CI

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'feature/**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Coverage tests
        run: sbt "test; coverageReport"

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Import signing PGP key
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
        run: |
          gpg --version
          echo "$PGP_SECRET" | gpg --import

      - name: Publish snapshot artifacts
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: sbt +publishSigned

      - name: Publish artifacts to Maven central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASS }}
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          DECLARED_VERSION=$(cat build.sbt | grep -oP "(?<=ThisBuild / version := \")((\d+\.)+\d+)(?=-SNAPSHOT\")")
          TAGGED_VERSION=$(echo ${{ github.ref }} | sed -e "s~^refs/tags/v~~")
          
          if [ $DECLARED_VERSION != $TAGGED_VERSION ]; then
              echo "Found $DECLARED_VERSION on build.sbt, but tagged $TAGGED_VERSION. Exiting..."
              exit 1
          fi
          
          # set the artifact version to DECLARED_VERSION
          sed -i -e "s~ThisBuild / version := \".*\"~ThisBuild / version := \"$DECLARED_VERSION\"~" build.sbt
          
          # publish to local repository, and then release bundle
          sbt "publishSigned; sonatypeBundleRelease"